version: '3'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data-directory:/data/db

  rabbitmq:
    image: rabbitmq:management
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5


  keycloak:
    image: protegeproject/keycloak
    # ports:
    #   - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_FRONTEND_URL: "http://webprotege-local.edu/auth"
      KEYCLOAK_IMPORT: /tmp/webprotege.json
      KEYCLOAK_HOSTNAME_ADMIN_URL: "http://webprotege-local.edu/auth"
    volumes:
      - keycloak-h2-directory:/opt/jboss/keycloak/standalone/data
      - ./keycloak:/tmp
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/auth/realms/master" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  minio:
    image: minio/minio
    command: [ "server", "/data" ]
    restart: always
    volumes:
     - minio_data:/data
    # ports:
      # - 9000:9000
      # - 9001:9001
    environment:
      MINIO_ROOT_USER: webprotege
      MINIO_ROOT_PASSWORD: webprotege

  webprotege-gwt-api-gateway:
    image: protegeproject/webprotege-gwt-api-gateway:1.0.3
    depends_on:
      keycloak:
        condition: service_healthy
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started

    environment:
      spring.zipkin.baseUrl: http://zipkin:9411
      JDK_JAVA_OPTIONS: --add-opens java.base/sun.net=ALL-UNNAMED
      SPRING_RABBITMQ_PUBLISHER_CONFIRM_TYPE: NONE
      SPRING_RABBITMQ_PUBLISHER_RETURNS: "FALSE"

  webprotege-gwt-ui-server:
    image: protegeproject/webprotege-gwt-ui-server:5.0.6-WHO
    depends_on:
      webprotege-gwt-api-gateway:
        condition: service_started
      keycloak:
        condition: service_healthy
    # ports:
      # - 8888:8080
    environment:
      minio.access.key: minioadmin
      minio.access.secret: minioadmin
      minio.endPoint: http://minio:9000
      webprotege.gwt-api-gateway.endPoint: http://webprotege-gwt-api-gateway:7777


  webprotege-authorization-service:
    image: protegeproject/webprotege-authorization-service:1.0.1
    depends_on:
      keycloak:
        condition: service_healthy
      mongo:
        condition: service_started
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      spring.data.mongodb.host: mongo
      spring.data.mongodb.database: webprotege
      keycloak.jwk-set-uri: http://keycloak:8080
      spring.zipkin.baseUrl: http://zipkin:9411
      JDK_JAVA_OPTIONS: --add-opens java.base/sun.net=ALL-UNNAMED

  webprotege-user-management-service:
    image: protegeproject/webprotege-user-management-service:1.0.0
    depends_on:
      keycloak:
        condition: service_healthy
      mongo:
        condition: service_started
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      JDK_JAVA_OPTIONS: --add-opens java.base/sun.net=ALL-UNNAMED

  webprotege-event-history-service:
    image: protegeproject/webprotege-event-history-service:1.0.1
    ports:
      - '5006:5006'
    depends_on:
      mongo:
        condition: service_started
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      JDK_JAVA_OPTIONS: --add-opens java.base/sun.net=ALL-UNNAMED
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006


  webprotege-backend-service:
    user: root
    image: protegeproject/webprotege-backend-service:1.2.2-SNAPSHOT
    ports:
      - '5005:5005'
    depends_on:
      mongo:
        condition: service_started
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      spring.zipkin.baseUrl: http://zipkin:9411
      webprotege.directories.data: /srv/webprotege
      webprotege.minio.access.key: minioadmin
      webprotege.minio.access.secret: minioadmin
      webprotege.minio.endPoint: http://minio:9000
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      JDK_JAVA_OPTIONS: --add-opens java.base/sun.net=ALL-UNNAMED
    volumes:
    - webprotege-data-directory:/srv/webprotege


  nginx:
    image: protegeproject/webprotege-nginx:latest
    hostname: webprotege-local.edu
    ports:
      - 80:80
    depends_on: 
      - webprotege-gwt-ui-server
      - keycloak

volumes:
  webprotege-data-directory:
  mongo-data-directory:
  keycloak-h2-directory:
  minio_data: