version: '3'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data-directory:/data/db

  pulsar:
    image: apachepulsar/pulsar:2.11.2
    user: root
    ports:
      - "8080:8080"
      - "6650:6650"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: /pulsar/bin/pulsar standalone
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/admin/v2/brokers/health"]
      interval: 2s
      timeout: 5s
      retries: 15
    restart: no

  keycloak:
    image: jboss/keycloak
    # ports:
    #   - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_FRONTEND_URL: "http://webprotege-local.edu/auth"

    volumes:
      - keycloak-h2-directory:/opt/jboss/keycloak/standalone/data
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/auth/realms/master" ]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio
    command: [ "server", "/data" ]
    restart: always
    volumes:
     - minio_data:/data
    # ports:
      # - 9000:9000
      # - 9001:9001
    environment:
      MINIO_ROOT_USER: webprotege
      MINIO_ROOT_PASSWORD: webprotege

  webprotege-gwt-ui-server:
    image: protegeproject/webprotege-gwt-ui-server:5.0.2-SNAPSHOT
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - 8888:8080
    environment:
      minio.access.key: minioadmin
      minio.access.secret: minioadmin
      minio.endPoint: http://minio:9000
      webprotege.gwt-api-gateway.endPoint: http://webprotege-gwt-api-gateway:7777

  webprotege-gwt-api-gateway:
    image: protegeproject/webprotege-gwt-api-gateway:0.1.2-SNAPSHOT

    ports:
      - '5005:5005'
    depends_on:
      pulsar:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      webprotege.pulsar.serviceHttpUrl: http://pulsar:8080
      webprotege.pulsar.serviceUrl: pulsar://pulsar:6650
      webprotege.pulsar.tenant: webprotege

      webprotege.pulsar.command-replies.subscriptionExpiraryTimeMinutes: 5
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  nginx:
    image: protegeproject/webprotege-nginx:latest
    hostname: webprotege-local.edu
    ports:
      - 80:80
    depends_on:
      - webprotege-gwt-ui-server
      - keycloak

volumes:
  webprotege-data-directory:
  mongo-data-directory:
  keycloak-h2-directory:
  minio_data:
  pulsardata:
  pulsarconf: